%YAML 1.2
---
version: 1
formatters:
  simple:
    format: '%(asctime)s - %(module)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
root:
  level: DEBUG
  handlers: [console]
